accelerator: auto
devices: auto
strategy: auto
use_distributed_sampler: true
precision: bf16-mixed
max_steps: 1000000
max_epochs: -1
log_every_n_steps: 10
gradient_clip_val: 1.0
ckpt_path: null
val_check_interval: 10000
check_val_every_n_epoch: null
